#!/bin/sh

./autogen.sh
./my-configure mingw
make clean
make -j4
cp src/RoguelikeFansBand.exe .
if [ -n "$1" ]
then
    file=RoguelikeFansBand-"$1".zip
else
    file=RoguelikeFansBand-"$(git describe)".zip
fi

rm $file
find ./lib -name Makefile -prune -o -name .deps -prune -o -print | zip $file -@
zip $file RoguelikeFansBand.exe readme.txt
